apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-dp
spec:
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - image: chancehee/gallery-post
          name: post
          env:
            - name: REDIS_HOST
              value: "redis-svc"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gallery-secret
                  key: REDIS_PASSWORD
            - name: GALLERY_DB_HOST
              value: "mysql-svc:3306"
            - name: GALLERY_DB_USER
              value: "root"
            - name: GALLERY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gallery-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: GALLERY_MEMBER_HOST
              value: "member-svc"
            # - name: BOOTSTRAP_SERVERS
            #   value: "kafka-svc:9092"
            - name: JPA_DDL_TYPE
              value: "update"
          ports:
            - containerPort: 8003

---
apiVersion: v1
kind: Service
metadata:
  name: post-svc
spec:
  ports:
    - port: 8003
  selector:
    app: post
