name: CI

on:
  push:
    branches:
      - front

env:
  IMAGE_NAME: gallery-react

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: D
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.FRONT_DOCKER_USERNAME }}
          password: ${{ secrets.FRONT_DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.FRONT_DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.FRONT_DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Set Kustomize
        uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          kustomize: '3.7.0'

      - name: Update kubernetes manifest
        run: |
          git checkout front-argo
          cd config/deploy/react/
          kustomize edit set image ${{ github.sha }}
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add .
          git commit -m 'k8s manifest for ${{ github.sha }}'
          git push origin
