name: CI

on:
  push:
    branches:
      - back-gallery # 트리거 브랜치
env:
  IMAGE_NAME: gallery-gallery

jobs:
  docker-build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./backend/gallery

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Retrieve application properties
        env:
          APPLICATION_PROPERTIES: ${{ secrets.GALLERY_APPLICATION_PROPERTIES }} # 시크릿에 등록시킨 application.yml 불러오기
        run: |
          mkdir ./src/main/resources
          touch ./src/main/resources/application.yml
          echo "${APPLICATION_PROPERTIES}" > ./src/main/resources/application.yml

      - name: Build Spring Boot application
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.BACK_DOCKER_USERNAME }} # chancehee 
          password: ${{ secrets.BACK_DOCKER_TOKEN }} # 도커 허브에서 생성한 토큰

      - name: Build Docker image
        run: docker build -t ${{ secrets.BACK_DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.BACK_DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  kustomize-update:
    runs-on: ubuntu-latest
    needs: docker-build-and-deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Switch to gallery-argo branch
        run: |
          git fetch
          git checkout gallery-argo

      - name: Set Kustomize
        uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          kustomize: "3.7.0"

      - name: Update kubernetes manifest
        run: |
          cd config/deploy/gallery/
          kustomize edit set image ${{ secrets.BACK_DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add .
          git commit -m 'k8s manifest for ${{ github.sha }}'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 자동으로 생성되도록 함
          branch: gallery-argo
